_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 256
hidden_dim:
    value: 128
lr:
    value: 0.001
movie_context_len:
    value: 19
num_epochs:
    value: 200
